version: '2'
services:
  postgres:
    image: postgres:12.7
    container_name: forestfinance
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=forest
      - POSTGRES_USER=forest
      - POSTGRES_PASSWORD=secret